const PAST_LIFE_TYPES=['knight','scholar','painter','royal','explorer','healer','oracle','pirate'];
const PAST_LIFE_ERAS=[
  {id:'egypt',a:{oracle:3,royal:2,knight:1},b:{scholar:3,healer:2,painter:1}},
  {id:'medieval',a:{knight:3,pirate:2,royal:1},b:{healer:3,painter:1,scholar:1}},
  {id:'renaissance',a:{painter:3,oracle:1,healer:1},b:{explorer:3,royal:2,pirate:1}},
  {id:'exploration',a:{explorer:3,pirate:2,knight:1},b:{scholar:3,oracle:2,painter:1}},
  {id:'industrial',a:{royal:3,pirate:1,explorer:1},b:{healer:3,oracle:2,painter:1}},
  {id:'modern',a:{pirate:3,painter:2,explorer:1},b:{scholar:2,oracle:3,healer:1}}
];
const pastLifeStages=new Set();
function trackPastLife(name,detail={}){if(pastLifeStages.has(name))return;pastLifeStages.add(name);if(typeof gtag==='function')gtag('event',name,{event_category:'past_life_story',app_language:i18n.getCurrentLanguage(),...detail})}
class PastLifeJourney{
  constructor(){this.index=0;this.scores={};this.selections=[];this.result=null;this.bind();this.reset();trackPastLife('past_life_view')}
  bind(){document.getElementById('start').addEventListener('click',()=>this.start());document.getElementById('next').addEventListener('click',()=>this.next());document.getElementById('retry').addEventListener('click',()=>this.start());document.getElementById('share').addEventListener('click',()=>this.share());document.getElementById('choice-a').addEventListener('click',()=>this.choose('a'));document.getElementById('choice-b').addEventListener('click',()=>this.choose('b'));document.querySelectorAll('[data-target-slug]').forEach(a=>a.addEventListener('click',()=>trackPastLife('past_life_related_click',{target_slug:a.dataset.targetSlug})));document.addEventListener('pastlife:language',()=>{if(document.getElementById('journey').classList.contains('active'))this.renderScene();if(document.getElementById('result').classList.contains('active'))this.renderResult()})}
  reset(){this.index=0;this.selections=[];this.result=null;this.scores=Object.fromEntries(PAST_LIFE_TYPES.map(type=>[type,0]))}
  show(id){document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.id===id))}
  start(){this.reset();this.show('journey');this.renderScene();trackPastLife('past_life_start')}
  renderScene(){const era=PAST_LIFE_ERAS[this.index],key=`eras.${era.id}`;document.getElementById('progress-label').textContent=i18n.format('journey.progress',{current:this.index+1,total:PAST_LIFE_ERAS.length});document.getElementById('bar').style.width=`${((this.index+1)/PAST_LIFE_ERAS.length)*100}%`;document.getElementById('era-year').textContent=i18n.t(`${key}.year`);document.getElementById('era-title').textContent=i18n.t(`${key}.title`);document.getElementById('scene').textContent=i18n.t(`${key}.scene`);for(const side of['a','b']){const upper=side.toUpperCase(),button=document.getElementById(`choice-${side}`);document.getElementById(`choice-${side}-icon`).textContent=i18n.t(`${key}.choice${upper}Icon`);document.getElementById(`choice-${side}-text`).textContent=i18n.t(`${key}.choice${upper}`);button.disabled=Boolean(this.selections[this.index]);button.classList.toggle('selected',this.selections[this.index]===side)}const next=document.getElementById('next');next.textContent=i18n.t(this.index===PAST_LIFE_ERAS.length-1?'journey.finish':'journey.next');next.classList.toggle('hidden',!this.selections[this.index]);requestAnimationFrame(()=>document.getElementById('scene').focus())}
  choose(side){if(this.selections[this.index])return;this.selections[this.index]=side;for(const[type,points]of Object.entries(PAST_LIFE_ERAS[this.index][side]))this.scores[type]+=points;this.renderScene()}
  next(){if(!this.selections[this.index])return;if(++this.index<PAST_LIFE_ERAS.length)this.renderScene();else this.complete()}
  complete(){this.result=PAST_LIFE_TYPES.reduce((best,type)=>this.scores[type]>this.scores[best]?type:best,PAST_LIFE_TYPES[0]);this.show('result');this.renderResult();trackPastLife('past_life_complete');if(typeof GameAds!=='undefined')GameAds.showInterstitial({onComplete:()=>{}})}
  renderResult(){const name=i18n.t(`types.${this.result}.name`),setting=i18n.t(`types.${this.result}.era`);document.getElementById('role-name').textContent=name;document.getElementById('role-setting').textContent=setting;document.getElementById('result-summary').textContent=i18n.format('result.summary',{name})}
  async share(){const lang=i18n.getCurrentLanguage(),url=`https://dopabrain.com/past-life/?lang=${lang}`;try{if(navigator.share)await navigator.share({title:i18n.t('app.shortTitle'),text:i18n.t('share.text'),url});else if(navigator.clipboard?.writeText)await navigator.clipboard.writeText(url);else throw Error('share unavailable');trackPastLife('past_life_share');const b=document.getElementById('share'),old=b.textContent;b.textContent=i18n.t('result.copied');setTimeout(()=>b.textContent=old,1500)}catch(error){if(error?.name!=='AbortError')console.warn('Share failed:',error?.message||error)}}
}
window.addEventListener('DOMContentLoaded',async()=>{await i18n.init();window.pastLifeJourney=new PastLifeJourney();document.getElementById('app-loader')?.remove();if(typeof GameAds!=='undefined')GameAds.init();if('serviceWorker'in navigator)navigator.serviceWorker.register('/past-life/sw.js',{scope:'/past-life/'}).catch(()=>{})});
